apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster

versions:
  kubernetes: "1.26.3"

cloudProvider:
  vmwareCloudDirector:
    vApp: kubeone

containerRuntime:
  containerd: {}

clusterNetwork:
  kubeProxy:
    skipInstallation: true
  cni:
    cilium:
      kubeProxyReplacement: strict
      enableHubble: true

addons: # https://docs.kubermatic.com/kubeone/v1.6/guides/addons/
  enable: true
  path: ./addons
  addons: # https://github.com/kubermatic/kubeone/tree/release/v1.6/addons
  - name: cluster-autoscaler
  - name: unattended-upgrades
  - name: csi-vmware-cloud-director
    params:
      clusterid: NO_RDE_kubeone
  # Set vCloud-CSI as default storage-class. Uncomment to enable, but consult README.md first for caveats!
  # - name: default-storage-class
  #   params:
  #     storageProfile: Ultra Fast Storage A # adjust to a storage profile of your choice, see "VCD UI -> Data Centers -> Storage -> Storage Policies"
