apiVersion: cluster.k8s.io/v1alpha1
kind: MachineDeployment
metadata:
  annotations:
    cluster.k8s.io/cluster-api-autoscaler-node-group-max-size: "5"
    cluster.k8s.io/cluster-api-autoscaler-node-group-min-size: "3"
    k8c.io/operating-system-profile: ""
  creationTimestamp: null
  name: kubeone-worker-pool
  namespace: kube-system
spec:
  minReadySeconds: 0
  replicas: 3
  selector:
    matchLabels:
      workerset: kubeone-worker-pool
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        v1.kubelet-config.machine-controller.kubermatic.io/EvictionHard: ""
        v1.kubelet-config.machine-controller.kubermatic.io/KubeReserved: cpu=200m,memory=300Mi
        v1.kubelet-config.machine-controller.kubermatic.io/MaxPods: "110"
        v1.kubelet-config.machine-controller.kubermatic.io/SystemReserved: cpu=200m,memory=200Mi
      creationTimestamp: null
      labels:
        workerset: kubeone-worker-pool
      namespace: kube-system
    spec:
      metadata:
        creationTimestamp: null
        labels:
          workerset: kubeone-worker-pool
      providerSpec:
        value:
          cloudProvider: vmware-cloud-director
          cloudProviderSpec:
            allowInsecure: false
            catalog: KubeOne
            cpuCores: 1
            cpus: 4
            diskSizeGB: 250
            ipAllocationMode: DHCP
            memoryMB: 8192
            metadata:
              KubeOneCluster: kubeone
            network: kubeone-routed-network
            organization: PRO-005019247
            storageProfile: '*'
            template: Ubuntu 20.04 Server
            vapp: kubeone
            vdc: kubernetes-demo
          operatingSystem: ubuntu
          operatingSystemSpec:
            distUpgradeOnBoot: false
          sshPublicKeys:
          - |
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2QKTfntKlsoo4ELBZgBLvIshQht2hzaQ7AGmJU2cxnt6cen7mwkqHkYA+ZoBBSi5DxcAGv1M5PX7ICiW8vdkHjStQzLXvXeov7YYKR9+WXBPhw5MF6O/PqW30Vf40EnRWdr0mlTcm/8BYai4DyJDNLayOxkefsVfhUDw42/nWK2uHEA/RzCLrYQhp4A6fP2YWXoGWNHzHuOfY1rea+TZkDStPcJQj07Qlvqpb9wk7O9VxaaxcsJbHQDpFzW4nWFYzb2AJUBbnQZoRDlx0GAYSVyEPXRIL7mpTUHKyZeLD5b46xvWyhynMGOfMChtihGX2ITdidLzd5WXs162pt0rhf/Y0aAwbgDN0R1UfS8l7dLiNojj4sZcZ717eEjaCGZUKBeNftHvKnF+G8YZHB3eOR2ryoNT2S5ZlwabJiOrP3V51us2KMlkvdeI81VeVLU+C39MY/jGipAkIsQil+XKLtw7HVSEZ+gH/3MmFeGrOM5wbiIatum15J0IGxGTma+E= admin@kubernetes
      versions:
        kubelet: 1.26.4
status: {}

---

