apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster

versions:
  kubernetes: "1.26.6"

cloudProvider:
  vmwareCloudDirector:
    vApp: kubeone

containerRuntime:
  containerd: {}

clusterNetwork:
  kubeProxy:
    skipInstallation: true
  cni:
    cilium:
      kubeProxyReplacement: strict
      enableHubble: true

features:
  openidConnect:
    enable: true # set to 'false' if you don't want to use OIDC for cluster authentication
    config: # see https://docs.kubermatic.com/kubeone/v1.6/tutorials/creating-clusters-oidc/ for further details
      issuerUrl: "https://dex.my-kubernetes.my-domain.com/dex" # adjust domain to your actual hostname (prefixed with "dex." subdomain), make sure you have a valid DNS records pointing to the edge gateway beforehand
      clientId: "kubernetes"
      # usernameClaim: "preferred_username"
      # usernameClaim: "email"
      # usernamePrefix: "-"
      usernamePrefix: "oidc:"
      groupsClaim: "groups"
      groupsPrefix: "oidc:"

addons: # https://docs.kubermatic.com/kubeone/v1.6/guides/addons/
  enable: true
  path: ./addons
  addons: # https://github.com/kubermatic/kubeone/tree/release/v1.6/addons
  - name: cluster-autoscaler
  - name: unattended-upgrades

  - name: csi-vmware-cloud-director
    params:
      clusterid: NO_RDE_kubeone
      storageProfile: Ultra Fast Storage A # adjust to a storage profile of your choice, see "VCD UI -> Data Centers -> Storage -> Storage Policies"

  # Set vCloud-CSI as default storage-class. Consult README.md for caveats!
  - name: default-storage-class
    params:
      storageProfile: Ultra Fast Storage A # adjust to a storage profile of your choice, see "VCD UI -> Data Centers -> Storage -> Storage Policies"
