---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ .Release.Name }}"
    app.kubernetes.io/component: config
    app.kubernetes.io/name: wireguard
  name: "{{ .Release.Name }}"
type: Opaque
stringData:
  wg0.conf: |
    # server
    [Interface]
    Address = {{ .Values.wireguard.serverAddress }}
    ListenPort = 51820
    PrivateKey = {{ .Values.wireguard.privateKey }}
    PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
    PostUp = sysctl -w -q net.ipv4.ip_forward=1; sysctl -w -q net.ipv4.conf.all.forwarding=1
    PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE
    PostDown = sysctl -w -q net.ipv4.ip_forward=0; sysctl -w -q net.ipv4.conf.all.forwarding=0
    SaveConfig = false

    # clients
    {{- range .Values.wireguard.clients }}
    [Peer]
    {{- if .name }}
    # name = {{ .name }}
    {{- end }}
    PublicKey = {{ .publicKey }}
    AllowedIPs = {{ .allowedIPs }}
    {{- end }}
