---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Release.Name }}"
    app.kubernetes.io/component: svc
    app.kubernetes.io/name: wireguard
  name: "{{ .Release.Name }}"
spec:
  ports:
  - nodePort: 32518
    port: 51820
    protocol: UDP
    targetPort: 51820
  selector:
    app: "{{ .Release.Name }}"
    app.kubernetes.io/component: interface
    app.kubernetes.io/name: wireguard
  type: NodePort
